// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddURL validates a single link and enqueues it in queueID. An empty
 * queueID means the main queue, which is where the intake field sends links
 * by default; links only wait when the caller picks a queue that is stopped.
 */
export function AddURL(rawURL: string, queueID: string): $CancellablePromise<$models.DownloadItem> {
    return $Call.ByID(4294886917, rawURL, queueID);
}

export function Cancel(id: string): $CancellablePromise<void> {
    return $Call.ByID(2191755235, id);
}

export function CancelBatch(ids: string[] | null): $CancellablePromise<$models.BatchResult> {
    return $Call.ByID(3900665653, ids);
}

export function CancelClipboardReview(): $CancellablePromise<void> {
    return $Call.ByID(3732774515);
}

export function ClearCompleted(): $CancellablePromise<void> {
    return $Call.ByID(2291046527);
}

export function Configuration(): $CancellablePromise<$models.Configuration> {
    return $Call.ByID(1495316273);
}

export function ConfirmClipboard(review: $models.ClipboardReview, queueID: string): $CancellablePromise<$models.ClipboardBatchResult> {
    return $Call.ByID(4241361135, review, queueID);
}

export function CreateQueue(name: string): $CancellablePromise<$models.DownloadQueue> {
    return $Call.ByID(2443955096, name);
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1990065762, id);
}

export function DeleteBatch(ids: string[] | null): $CancellablePromise<$models.BatchResult> {
    return $Call.ByID(2756503086, ids);
}

export function DeleteQueue(id: string): $CancellablePromise<void> {
    return $Call.ByID(42443685, id);
}

export function MoveDown(id: string): $CancellablePromise<void> {
    return $Call.ByID(2526363752, id);
}

/**
 * MoveToQueue repoints every listed download at queueID in one operation, so
 * a context-menu selection does not turn into one IPC call per row.
 */
export function MoveToQueue(ids: string[] | null, queueID: string): $CancellablePromise<$models.BatchResult> {
    return $Call.ByID(897236392, ids, queueID);
}

export function MoveUp(id: string): $CancellablePromise<void> {
    return $Call.ByID(572824833, id);
}

export function OpenDirectory(id: string): $CancellablePromise<void> {
    return $Call.ByID(4113378380, id);
}

export function OpenFile(id: string): $CancellablePromise<void> {
    return $Call.ByID(1958968983, id);
}

export function Pause(id: string): $CancellablePromise<void> {
    return $Call.ByID(1037007909, id);
}

export function PauseBatch(ids: string[] | null): $CancellablePromise<$models.BatchResult> {
    return $Call.ByID(1233517627, ids);
}

export function ReadClipboard(): $CancellablePromise<string> {
    return $Call.ByID(3110812313);
}

export function Remove(id: string): $CancellablePromise<void> {
    return $Call.ByID(1395520005, id);
}

export function RemoveBatch(ids: string[] | null): $CancellablePromise<$models.BatchResult> {
    return $Call.ByID(1701427419, ids);
}

export function RenameQueue(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3260093674, id, name);
}

export function Restore(): $CancellablePromise<void> {
    return $Call.ByID(1101632249);
}

export function Resume(id: string): $CancellablePromise<void> {
    return $Call.ByID(2476070530, id);
}

export function ResumeBatch(ids: string[] | null): $CancellablePromise<$models.BatchResult> {
    return $Call.ByID(557028110, ids);
}

export function Retry(id: string): $CancellablePromise<void> {
    return $Call.ByID(1182829889, id);
}

export function RetryBatch(ids: string[] | null): $CancellablePromise<$models.BatchResult> {
    return $Call.ByID(976703783, ids);
}

export function ReviewClipboard(text: string): $CancellablePromise<$models.ClipboardReview> {
    return $Call.ByID(2007921205, text);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(2987688963);
}

export function Snapshot(): $CancellablePromise<$models.ServiceSnapshot> {
    return $Call.ByID(365975013);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1627660663);
}

export function StartQueue(id: string): $CancellablePromise<void> {
    return $Call.ByID(1087345150, id);
}

export function StopQueue(id: string): $CancellablePromise<void> {
    return $Call.ByID(3238593792, id);
}
