// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BatchFailure reports one item of a bulk action that did not apply.
 */
export interface BatchFailure {
    "id": string;
    "reason": string;
}

/**
 * BatchResult is the outcome of a bulk action over a selection of downloads.
 */
export interface BatchResult {
    "succeeded": string[] | null;
    "failures": BatchFailure[] | null;
}

export interface ClipboardBatchResult {
    "results": ClipboardResult[] | null;
}

export interface ClipboardResult {
    "url": string;
    "status": string;
    "reason"?: string;
    "item"?: DownloadItem | null;
}

export interface ClipboardReview {
    "accepted": ClipboardURL[] | null;
    "duplicates": ClipboardURL[] | null;
    "rejected": ClipboardURL[] | null;
}

export interface ClipboardURL {
    "url": string;
    "reason"?: string;
}

export interface Configuration {
    "downloadDirectory": string;
    "activeLimit": number;
    "connections": number;
    "maxRetries": number;
}

export interface DownloadItem {
    "id": string;
    "url": string;
    "gid"?: string;
    "state": DownloadState;
    "queueId": string;
    "queuePaused"?: boolean;
    "destination": string;
    "path"?: string;
    "addedAt": string;
    "totalBytes": number;
    "completedBytes": number;
    "downloadSpeed": number;
    "attempts": number;
}

/**
 * DownloadQueue groups downloads behind one start/stop control. Downloads are
 * only scheduled while their queue is running, so a queue that is stopped
 * holds its downloads — including ones that were already running when it was
 * stopped, which are paused and marked QueuePaused so starting the queue
 * resumes them instead of losing them.
 */
export interface DownloadQueue {
    "id": string;
    "name": string;
    "running": boolean;
    "builtIn": boolean;
}

export enum DownloadState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateQueued = "queued",
    StateActive = "active",
    StatePaused = "paused",
    StateFailed = "failed",
    StateComplete = "complete",
};

export interface ServiceSnapshot {
    "items": DownloadItem[] | null;
    "queues": DownloadQueue[] | null;
    "configuration": Configuration;
}
