// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddURL(arg1) {
  return window['go']['main']['App']['AddURL'](arg1);
}

export function Configuration() {
  return window['go']['main']['App']['Configuration']();
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}
