// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddURL(arg1) {
  return window['go']['main']['App']['AddURL'](arg1);
}

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function CancelClipboardReview() {
  return window['go']['main']['App']['CancelClipboardReview']();
}

export function Configuration() {
  return window['go']['main']['App']['Configuration']();
}

export function ConfirmClipboard(arg1) {
  return window['go']['main']['App']['ConfirmClipboard'](arg1);
}

export function MoveDown(arg1) {
  return window['go']['main']['App']['MoveDown'](arg1);
}

export function MoveUp(arg1) {
  return window['go']['main']['App']['MoveUp'](arg1);
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function Resume(arg1) {
  return window['go']['main']['App']['Resume'](arg1);
}

export function Retry(arg1) {
  return window['go']['main']['App']['Retry'](arg1);
}

export function ReviewClipboard(arg1) {
  return window['go']['main']['App']['ReviewClipboard'](arg1);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}
