// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddURL(arg1) {
  return window['go']['main']['App']['AddURL'](arg1);
}

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function CancelClipboardReview() {
  return window['go']['main']['App']['CancelClipboardReview']();
}

export function ClearCompleted() {
  return window['go']['main']['App']['ClearCompleted']();
}

export function Configuration() {
  return window['go']['main']['App']['Configuration']();
}

export function ConfirmClipboard(arg1) {
  return window['go']['main']['App']['ConfirmClipboard'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function MoveDown(arg1) {
  return window['go']['main']['App']['MoveDown'](arg1);
}

export function MoveUp(arg1) {
  return window['go']['main']['App']['MoveUp'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function Restore() {
  return window['go']['main']['App']['Restore']();
}

export function Resume(arg1) {
  return window['go']['main']['App']['Resume'](arg1);
}

export function Retry(arg1) {
  return window['go']['main']['App']['Retry'](arg1);
}

export function ReviewClipboard(arg1) {
  return window['go']['main']['App']['ReviewClipboard'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}
