// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddURL(arg1:string):Promise<main.DownloadItem>;

export function Configuration():Promise<main.Configuration>;

export function Snapshot():Promise<main.ServiceSnapshot>;
